### ISSUE TITLE
couchbeam_changes_stream:loop crashes

### ISSUE THREAD

**Issue by cwmichi** [benoitc/couchbeam#132]
Hi, 

I am using couchbeam with the current version 1.1.8 (tag) and getting an error during the call with couchbeam_changes:follow

1> couchbeam_changes:follow({db,{server,<<"http://localhost:5984">>,[]},<<"my_db1">>,[]}, [continuous,include_docs]).
{ok,#Ref<0.0.1.11618>}

At first I am receiving the changes, but then the connecting interrupts with {closed, timeout}.

[error] CRASH REPORT Process <0.748.0> with 0 neighbours exited with reason: {error,{closed,timeout}} in couchbeam_changes_stream:loop/1 line 178

I don´t get this error with couchbeam version 1.1.6 (tag), any hint´s ?

Michael

**Comment by benoitc** [comment]
using the same version of couchdb?

**Comment by cwmichi** [comment]
Hey benoitc, sorry I mean:
couchbeam with the version tag 1.1.8 
my CouchDB version is currently 1.6.1 from the apache website.

**Comment by benoitc** [comment]
should be fixed in latest release. Let me know :)

**Comment by benoitc** [comment]
no answer. closing issue.
