### ISSUE TITLE
couchbeam:start/0 is gone, docs now incorrect, how to start?

### ISSUE THREAD

**Issue by nlfiedler** [benoitc/couchbeam#135]
Now that the couchbeam module lost the start/0 and stop/0 (and version/0) functions, how are we to start the couchbeam application? Sure, I could copy the code from before the change in November, but that seems less than ideal. Not to mention the docs and README examples are now wrong. Seems it was better to have these functions, if for no other reason than convenience.

**Comment by benoitc** [comment]
using latest erlang (since 17) : `application:ensure_all_started(couchbeam)` will. Or let the release do it. We can of course add this functions back if you want to.

**Comment by nlfiedler** [comment]
Indeed you are correct, I cannot see why I didn't realize the answer sooner. Thanks
