### ISSUE TITLE
errors in couchbeam_view_stream:do_init_stream

### ISSUE THREAD

**Issue by lazedo** [benoitc/couchbeam#148]
Hi,
is there a reason to exit instead of returning error in do_init_stream ?
https://github.com/benoitc/couchbeam/blob/master/src/couchbeam_view_stream.erl#L123-L125
i think that it should since we are initiating the streaming.

i can make a PR if you agree on this.
thanks

**Comment by benoitc** [comment]
if it's still current, of course that would be a good pr :)
