### ISSUE TITLE
relax hackney version

### ISSUE THREAD

**Issue by dc0d** [benoitc/couchbeam#161]
Currently `hackney` version is a fixed one in `couchbeam` (at the time `1.6.2`). And that [makes it hard](https://elixirforum.com/t/dependency-conflict/2599) to use `couchbeam` with other libraries like `httpoison` which depend on `hackney`.

The `hex` package is used - with Elixir.

If it is possible, it would help, to relax the version of `hackney` (like say `~> 1.6`).

**Comment by benoitc** [comment]
fixed by d7c3f476287467291c065d3ba4c58bdf8d990923 now only building using rebar3
