### ISSUE TITLE
hmac/3 getting depracated on OTP24

### ISSUE THREAD

**Issue by javierg** [benoitc/couchbeam#190]
`hmac/3` is being scheduled for removal on [OTP-24](http://erlang.org/doc/general_info/scheduled_for_removal.html#functions-scheduled-for-removal-in-otp-24) The project needs to switch to `mac/4`.

I think this functions are sued to oauth authentication. Am I wrong?

**Comment by benoitc** [comment]
compatibility is fixed in latest version :) But yes it's used for oauth
